// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message kinds the frontend sends and receives. Their bodies are opaque to Rust.
 */
export type AppKind = "presence" | "deskAnnounce" | "deskRequest" | "deskState" | "deskOps" | "deskDigest" | "values";
