// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a forwarded message must not go: back to the input's sender.
 */
export type Avoid = { 
/**
 * The endpoint the input arrived on; if it is an output (replies), that output is skipped.
 */
endpointId: string | null, 
/**
 * The sender's address, e.g. "192.168.1.30:8000".
 */
remote: string | null, };
