// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An earlier version of a shared desk.
 */
export type Backup = { 
/**
 * A `.json` preset file (import it to restore it as a copy).
 */
path: string, savedAtMs: number, };
