// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugEvent } from "./DebugEvent";

export type DebugBatch = { events: Array<DebugEvent>, 
/**
 * Events discarded since the previous batch because the UI was not keeping up.
 */
dropped: number, totalDropped: number, };
