// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugKind } from "./DebugKind";
import type { Direction } from "./Direction";
import type { OscPacketView } from "./OscPacketView";
import type { Transport } from "./Transport";

export type DebugEvent = { seq: number, 
/**
 * Wall-clock time in microseconds since the Unix epoch.
 */
tsMicros: number, kind: DebugKind, direction: Direction | null, 
/**
 * Desk (open preset) the endpoint belongs to; `None` for app-wide events.
 */
desk: string | null, endpointId: string, endpointName: string, transport: Transport | null, 
/**
 * Local socket address, e.g. "192.168.1.20:53211".
 */
local: string | null, 
/**
 * Remote socket address the packet went to / came from.
 */
remote: string | null, 
/**
 * The raw OSC packet bytes, exactly as handed to / received from the socket
 * (before TCP framing is applied / after it is removed).
 */
bytes: Array<number>, 
/**
 * Number of bytes actually written to the wire, including TCP framing. `None` when it
 * cannot be known exactly (e.g. inbound TCP streams).
 */
wireLen: number | null, decoded: OscPacketView | null, decodeError: string | null, 
/**
 * OS / transport error for this packet or lifecycle event, verbatim.
 */
error: string | null, 
/**
 * Human-readable note for info events.
 */
message: string | null, 
/**
 * Id of the widget that caused an outbound packet, if any.
 */
source: string | null, 
/**
 * True for an outbound packet that was held back because output is paused.
 */
blocked: boolean, };
