// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EndpointStats = { txPackets: number, txBytes: number, rxPackets: number, rxBytes: number, errors: number, 
/**
 * Outbound packets held back because output is paused.
 */
blocked: number, lastActivityMicros: number | null, };
