// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointKind } from "./EndpointKind";
import type { EndpointState } from "./EndpointState";
import type { EndpointStats } from "./EndpointStats";
import type { Transport } from "./Transport";

export type EndpointStatus = { 
/**
 * The desk (open preset) this endpoint belongs to. Ids are unique per desk only.
 */
desk: string, id: string, name: string, kind: EndpointKind, transport: Transport, state: EndpointState, local: string | null, remote: string | null, 
/**
 * Last error, client count, joined group, ... Shown next to the state in the UI.
 */
detail: string | null, stats: EndpointStats, };
