// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscArg } from "./OscArg";

/**
 * One OSC message that arrived on an endpoint somebody listens to.
 */
export type InboundMessage = { 
/**
 * The DebugEvent it was recorded as, so TRAFFIC can show what input mapping did with it.
 */
seq: number, desk: string, endpointId: string, remote: string, address: string, args: Array<OscArg>, };
