// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscPacketView } from "./OscPacketView";

/**
 * A successfully decoded inbound packet, forwarded to the frontend for widget feedback.
 */
export type IncomingOsc = { desk: string, endpointId: string, remote: string | null, packet: OscPacketView, };
