// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TcpFraming } from "./TcpFraming";
import type { Transport } from "./Transport";

export type InputConfig = { id: string, name: string, enabled: boolean, transport: Transport, 
/**
 * Local address to listen on. "0.0.0.0" listens on all IPv4 interfaces.
 */
bindAddress: string, port: number, 
/**
 * UDP only: multicast group to join (e.g. "239.0.0.1").
 */
multicastGroup: string | null, 
/**
 * TCP only.
 */
framing: TcpFraming, };
