// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InboundMessage } from "./InboundMessage";

export type InputBatch = { messages: Array<InboundMessage>, 
/**
 * Messages discarded since the previous batch because the queue was full (a flood).
 */
dropped: number, totalDropped: number, };
