// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

export type LocalStatus = { peerId: string, fingerprint: string, instanceId: string, profile: Profile, 
/**
 * Set if the saved device identity could not be read (a temporary one is in use).
 */
identityError: string | null, };
