// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A local network interface address, used by the UI to offer bind addresses and
 * directed-broadcast targets. Nothing is chosen automatically.
 */
export type NetInterface = { name: string, ip: string, prefixLen: number, netmask: string, 
/**
 * IPv4 directed broadcast address for this subnet, if it has one.
 */
broadcast: string | null, isLoopback: boolean, isIpv6: boolean, isUp: boolean, };
