// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an inbound packet came from, when it isn't the outside world. Such packets are shown
 * in TRAFFIC but never drive a widget.
 */
export type Origin = "self" | "peer";
