// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscTimeTag } from "./OscTimeTag";

/**
 * One OSC argument. The `type` tag is the OSC 1.0/1.1 typetag character, so what the user
 * picks in the UI is exactly what appears in the typetag string on the wire.
 */
export type OscArg = { "type": "i", "value": number } | { "type": "f", "value": number } | { "type": "s", "value": string } | { "type": "b", "value": Array<number> } | { "type": "h", "value": number } | { "type": "d", "value": number } | { "type": "c", "value": string } | { "type": "r", "value": number } | { "type": "m", "value": [number, number, number, number] } | { "type": "t", "value": OscTimeTag } | { "type": "T" } | { "type": "F" } | { "type": "N" } | { "type": "I" } | { "type": "[", "value": Array<OscArg> };
