// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscArg } from "./OscArg";

export type OscMessage = { address: string, args: Array<OscArg>, };
