// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscArg } from "./OscArg";
import type { OscTimeTag } from "./OscTimeTag";

/**
 * A decoded packet, as shown in the debug view.
 */
export type OscPacketView = { "kind": "message", address: string, 
/**
 * Typetag string exactly as encoded, e.g. ",fi".
 */
typetags: string, args: Array<OscArg>, } | { "kind": "bundle", timetag: OscTimeTag, content: Array<OscPacketView>, };
