// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NTP-style time tag (seconds since 1900 + 2^-32 fractions).
 */
export type OscTimeTag = { seconds: number, fractional: number, };
