// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TcpFraming } from "./TcpFraming";
import type { Transport } from "./Transport";
import type { UdpMode } from "./UdpMode";

export type OutputConfig = { id: string, name: string, enabled: boolean, transport: Transport, 
/**
 * IP address or hostname of the receiver (or broadcast / multicast address).
 */
host: string, port: number, 
/**
 * UDP only.
 */
mode: UdpMode, 
/**
 * Local address to send from. "0.0.0.0" lets the OS pick the interface.
 */
bindAddress: string, 
/**
 * Local source port. 0 lets the OS pick an ephemeral port.
 */
localPort: number, 
/**
 * UDP multicast only.
 */
multicastTtl: number, 
/**
 * UDP multicast only: receive our own multicast packets on this host.
 */
multicastLoop: boolean, 
/**
 * TCP only.
 */
framing: TcpFraming, 
/**
 * TCP only: delay between reconnect attempts.
 */
reconnectMs: number, };
