// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connected peer, as announced to the frontend.
 */
export type PeerInfo = { peerId: string, fingerprint: string, name: string, color: number, appVersion: string, address: string, };
