// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerSource } from "./PeerSource";
import type { PeerState } from "./PeerState";
import type { PeerStats } from "./PeerStats";

export type PeerStatus = { 
/**
 * Known once a connection was authenticated.
 */
peerId: string | null, fingerprint: string | null, 
/**
 * Where it is (or is being dialled), e.g. "192.168.1.30:9701".
 */
address: string, source: PeerSource, state: PeerState, name: string | null, color: number | null, appVersion: string | null, rttMs: number | null, 
/**
 * How far its clock is ahead of this one.
 */
clockOffsetMs: number | null, connectedSinceMs: number | null, stats: PeerStats, lastError: string | null, };
