// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerStats = { rxMsgs: number, txMsgs: number, rxBytes: number, txBytes: number, 
/**
 * Inbound messages refused: over the rate limit or malformed.
 */
rejected: number, 
/**
 * Live values not sent because the peer was too slow (newer ones replace them).
 */
droppedValues: number, };
