// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresetSummary = { id: string, name: string, updatedAt: string | null, fileName: string, 
/**
 * Set when the file exists but could not be read; the preset is listed anyway so the
 * user can see (and delete) it rather than having it silently vanish.
 */
error: string | null, };
