// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this device shows up to others.
 */
export type Profile = { name: string, 
/**
 * An index into the frontend's peer palette.
 */
color: number, };
