// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { id: string, name: string, savedAt: string | null, 
/**
 * How many desks it holds.
 */
desks: number, fileName: string, 
/**
 * Set when the file exists but could not be read (listed anyway, to delete it).
 */
error: string | null, };
