// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a run ended.
 */
export type SeqEnd = "done" | "stopped" | "replaced" | "deskClosed";
