// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeqEnd } from "./SeqEnd";
import type { SeqState } from "./SeqState";

/**
 * Where a run is. Only the latest of each run reaches the UI.
 */
export type SeqProgress = { desk: string, widget: string, 
/**
 * Increases with every start, so progress of an earlier run is recognised as stale.
 */
run: number, state: SeqState, 
/**
 * The step sent last (0-based); none yet.
 */
step: number | null, 
/**
 * The pass it is in, from 1.
 */
pass: number, 
/**
 * The wait after the step sent last, until the next (or the end), in ms.
 */
waitMs: number | null, 
/**
 * What was left of that wait when this was reported (it stops going down while paused).
 */
leftMs: number | null, 
/**
 * When this was reported: wall-clock microseconds since the Unix epoch.
 */
atMicros: number, ended: SeqEnd | null, 
/**
 * How often it fell behind and resynced.
 */
late: number, };
