// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeqStep } from "./SeqStep";

export type SeqPlan = { 
/**
 * Every step goes to these outputs of the run's desk.
 */
outputIds: Array<string>, steps: Array<SeqStep>, 
/**
 * Passes to play; `None` plays forever.
 */
count: number | null, };
