// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OscMessage } from "./OscMessage";

/**
 * One message of a sequence and the wait after it.
 */
export type SeqStep = { 
/**
 * The step's id in the widget, so an edited plan continues after the step sent last.
 */
id: string, message: OscMessage, delayMs: number, };
