// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of the skins directory: the skin, or why it couldn't be read (listed anyway, so
 * it can be seen and deleted rather than silently vanishing).
 */
export type SkinFile = { id: string, skin: unknown, error: string | null, };
