// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalStatus } from "./LocalStatus";
import type { PeerStatus } from "./PeerStatus";
import type { SyncConfig } from "./SyncConfig";

export type SyncStatus = { local: LocalStatus, config: SyncConfig, 
/**
 * The joined session's name, if any.
 */
session: string | null, 
/**
 * The port actually listened on.
 */
listening: number | null, listenError: string | null, discoveryActive: boolean, discoveryError: string | null, peers: Array<PeerStatus>, blocked: Array<string>, };
