// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppKind } from "./AppKind";
import type { PeerInfo } from "./PeerInfo";

/**
 * What the frontend receives, in order per peer: `up`, its messages, then `down`.
 */
export type SyncEvent = { "type": "up", peer: PeerInfo, } | { "type": "down", peer: string, reason: string, } | { "type": "message", peer: string, kind: AppKind, desk: string | null, 
/**
 * JSON, checked for well-formedness only: the frontend validates it.
 */
body: unknown, };
