// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncConfig = { 
/**
 * TCP port to listen on. If it is taken, a free port is used instead (and reported).
 */
port: number, 
/**
 * Find apps in the same session on the LAN (mDNS).
 */
discovery: boolean, 
/**
 * `host:port` of apps to connect to directly (when discovery can't reach them).
 */
manualPeers: Array<string>, };
