// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How OSC packets are delimited on a TCP stream.
 */
export type TcpFraming = "slip" | "lengthPrefix";
